javalinversion: 1.0.1
repourl: https://github.com/javalin/javalin.github.io
description: Javalin - Create REST APIs in Java or Kotlin. Javalin is a lightweight Java and Kotlin web framework.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
